spring:
  application:
    name: scfl-eureka-server
#---------------------------------------------------------------------
server:
  port: 50000
#---------------------------------------------------------------------
eureka:
  instance:
    prefer-ip-address: true
    status-page-url-path: /actuator/info #eureka注册中心的url link
    health-check-url-path: /actuator/health #健康检查的url
    hostname: localhost
  client:
    register-with-eureka: true #是否注册到注册中心
    fetch-registry: false #是否从注册中心拉取注册服务列表
    service-url:
      defaultZone: http://localhost:50000/eureka/
