# -- GITHUB Config
server:
  port: 8769
spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/KoneLu/easy_cloud
          search-paths: config-repo
          #  username:
          #  password:
          default-label: master

eureka:
  instance:
    prefer-ip-address: true
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:50000/eureka/